id: P3BB109E1
initial_creation_type: input
source_metadata:
  title: Do Khyentse Yeshe Dorje Series
  language: fr
  description: 'A series of texts associated with the treasure-revealer Do Khyentse
    Yeshe Dorje (mdo mkhyen brtse ye shes rdo rje, 1800–1866), renowned as the ''mind
    emanation'' of Jigme Lingpa:'
  volume:
    4d80e5f5a4f8483288314228b973ce82:
      title: 'The Truthful Words of a Sage: An Aspiration Prayer from the Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī'
      parent: Aspiration Prayers
    aa235bf385db4f578b95929717fb6c6e:
      title: Heart of Vajrasattva—The Heart of Confession, the King of Purification
        Practices, from 'The Immaculate Secret Vajrasattva'
      parent: Confession
    40c63b06a8924d38bc6c3527a2e4b670:
      title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
      parent: Guru Rinpoche Prayers
    6414d58fd734453d87270ac082defdba:
      title: 'The Lightning Bolt of Compassion: A Short Prayer that Spontaneously
        Fulfils All Wishes (Sampa Lhundrupma)'
      parent: Guru Rinpoche Prayers
    e065379cab4e470aa8a133909aac02d2:
      title: The Lineage Prayer for the Natural Liberation of Grasping (Dzinpa Rangdrol)
      parent: Lineage Prayers
    ae44328bf8a349ba8031e6c7668871ab:
      title: 'The Hook Which Invokes the Blessings: A Supplication to the Life and
        Liberation of Rigdzin Jalü Dorje'
      parent: Prayers
    b662dc1d95c24d81aa0cc8fd77fcd5a2:
      title: The Recitation for the Gradual Path of the Preliminaries from The Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī
      parent: Preliminaries
created_at: '2022-02-28T22:55:15.000221'
last_modified_at: '2022-02-28T22:55:15.000223'
